# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlgoliaAgain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlgoliaAgain

pod 'InstantSearch', '~> 7'
pod 'AlgoliaSearchClient', '~> 8'
pod 'SDWebImage', '~> 5'

end
